### ISSUE TITLE
Git output with ANSI escape codes are not handled (e.g., diff)

### ISSUE THREAD

**Issue by stuckj** [alpine-docker/git#11]
By default, git outputs diff output with ANSI escape codes to colorize it. While, this can be disabled, it is convenient. However, with this container the output shows the code rather than actually handling them. I believe this requires some configuration in the image to be able to properly handle the ANSI escape codes (potentially changing the pager).

**Comment by ozbillwang** [comment]
Can you run with option `--no-color` with log or show command?

    docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git diff --no-color

This option works for log, show, and other subcommands as well.

**Comment by stuckj** [comment]
Potentially. I can (and have for now) disable color via the `ui = false` setting in the `[color]` section of `.gitconfig`. However...colorization is really helpful so it would be nice if it was supported. :)

**Comment by ozbillwang** [comment]
fixed with #12
