### ISSUE TITLE
Add more detailed example for non-root user run

### ISSUE THREAD

**Issue by t-kanstantsin** [alpine-docker/git#13]
I'm not guru of docker and spent some time to run git commands as non-root.
[Here](https://github.com/alpine-docker/git/issues/7#issuecomment-375851107) recommend build new new image from original one and define correct user access. It seem bit strange - each developer should create own git image.

In [this question on stackoverflow](https://stackoverflow.com/questions/54007595/how-can-you-run-a-git-container-as-the-current-user) possible workaround.

```sh
docker run -it --rm
       --user $(id -u):$(id -g)
       -v $HOME:$HOME:rw
       -v /etc/passwd:/etc/paswd:ro
       -v /etc/group:/etc/group:ro
       -v $PWD:$PWD:rw
       -w $PWD
       alpine/git
       clone ...
```

And as mentioned torek:

> there's no guarantee that these files suffice (some systems use password databases). It's not clear where the "No user exists for ..." message is coming from. It's also not clear whether -v allows files at all—the description in the docker run documentation refers to directories, not files.

I don't know if this solution quite good and corresponds "best practices" of docker.
But if it does - I suggest add this command in readme examples

**Comment by ozbillwang** [comment]
I didn't have the problem in that question on stackoverflow you pasted when run docker with non-root user

Reminder, that stackoverflow question is accepted by the owner self.
