### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by oliv3r** [alpine-docker/git#14]
To ensure future stability of this container, start adding some unit tests.

Since this is a mainly docker focused product, try to stick with docker supplied infra; https://docs.docker.com/docker-hub/builds/automated-testing/

**Comment by ozbillwang** [comment]
something like this: https://github.com/sstephenson/bats ?

**Comment by oliv3r** [comment]
Yeah, I've used bats and it's quite nice; but I've since discovered https://github.com/kward/shunit2 which I found to be even nicer/more feature full.

**Comment by ozbillwang** [comment]
stale issue, no update, closed

**Comment by oliv3r** [comment]
@ozbillwang i don't think the issue is stale; i think this issue exists to track #10  ...

**Comment by ozbillwang** [comment]
ok, let's not work on that hard. 

the unit test is for git funcitons and feature. But in our case, we just install it directly.
