### ISSUE TITLE
SSL Internal CA and certificates

### ISSUE THREAD

**Issue by gknepper** [alpine-docker/git#15]
Hi There,

I 'm trying to fing a way to use a internal CA to accept a internal SSL certificate and clone from a https internal git repository? 

Thanks

**Comment by ozbillwang** [comment]
Is this question about this docker image or just common usage of “git”?

If it is second, stackoverflow website would be better place to ask for help

**Comment by ozbillwang** [comment]
This is git global setting, which you can set in `~/.gitconfig`

In fact, after you run above git command, it will update `~/.gitconfig` at your home directly. 

So will it be fine to run with 

```
docker run -ti --rm -v ~/.gitconfig:/root/.gitignore <rest commands>
```
