### ISSUE TITLE
docker run alpine/git -> push? 

### ISSUE THREAD

**Issue by cpolzer** [alpine-docker/git#17]
Hello, 

sorry for the question about usage of this docker image.

How would one issue a "git push" ?

`docker run -v {pwd}:/root alpine/git:latest push --dry-run`
Fails with error  "fatal: not a git repository (or any parent up to mount point /)"

I would be happy to issue a pr and adding this to the readme/docs

Thanks in advance

**Comment by ozbillwang** [comment]
I guess you should set the workdir with run command

    docker run -v {pwd}:/root -w /root alpine/git:latest push --dry-run
