### ISSUE TITLE
Modernise usage of Docker Hub (link to Dockerfile & automated builds from alpine base image)

### ISSUE THREAD

**Issue by MPV** [alpine-docker/git#18]
Hi,
Would you be open to modernise the usage of Docker hub for this image/repo?

1. No Dockerfile shown:

Today you can't see any `Dockerfile` here https://hub.docker.com/r/alpine/git/

This, in combination with that it's not easy to find this GitHub repo from the above page, makes this image seem not-so-trustworthy.

2. No automated builds

If the base image `alpine` is updated, this image isn't rebuilt and kept up-to-date.

Would you be open to adding this?

**Comment by ozbillwang** [comment]
1. No Dockerfile shown:

updated the `readme` in hub.docker.com with github repo url and travis ci build url.

2. No automated builds

set cronjob in travis.ci to run automation build every month, it will generate two tags:

* incremental release / tag version
* git version - `alpine/git:v${GIT_VERSION}`
