### ISSUE TITLE
Multiple architectures

### ISSUE THREAD

**Issue by alejandro-colomar** [alpine-docker/git#21]
Could you create images for architectures other than amd64?

I want to use it both in amd64 and in the Raspberry pi, but it is arm64/v8.

Right now I need to use alpine:latest, and then install git, which is not very complicated, but it could be nicer :)

**Comment by ozbillwang** [comment]
If you need, maybe you can raise PR for this request?

**Comment by alejandro-colomar** [comment]
I'd like to do it, but I don't know how to write the code for it.

**Comment by ozbillwang** [comment]
understood. I didn’t run with it with other platform, so it is not in my work list
