### ISSUE TITLE
Git log returns no output when performing revision selection

### ISSUE THREAD

**Issue by oyebayo** [alpine-docker/git#22]
When executing a revision selection with git on alpine, the output is always nothing. For example
`git log master..experiment` 
always returns nothing. Similarly,
`git log ^master experiment`
returns nothing. Other `git log` commands work as expected

This seems to be peculiar to alpine, as I can see this behaviour even in the latest version (Alpine 3.12, git 2.26.2)

**Comment by ozbillwang** [comment]
did you checkout the branch `experiment` before you run the command?

**Comment by oyebayo** [comment]
I can see that that was the issue, @ozbillwang. I am using alpine docker images in my CI pipeline and comparing two branches. Prefixing them both with "origin" gave me the expected result. Thank you.
