### ISSUE TITLE
linux/arm64 architecture support

### ISSUE THREAD

**Issue by moikot** [alpine-docker/git#25]
Since you've just implemented multi-arch, would it be possible to add linux/arm64 architecture so that the image can be used on Raspberry Pi?

**Comment by masip85** [comment]
I am seeking the same, I've tried:

```
FROM arm64v8/alpine:3.7
LABEL maintainer Bill Wang <ozbillwang@gmail.com>

RUN apk --update add git less openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

RUN git config user.name "xxxx" && \
         git config user.email "xxxx"

VOLUME /git
WORKDIR /git

ENTRYPOINT ["git"]
CMD ["--help"]
``` 

But:
_fatal: not in a git directory_

**Comment by ozbillwang** [comment]
No idea of the image `arm64v8/alpine:3.7`

@barthy1 Do you have any inputs about this topic?

**Comment by ozbillwang** [comment]
@masip85 

I guess you didn't run the container properly. 

```
docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git <git_command>
```

Your error is about you didn't mount the git repo directory into container.

**Comment by ozbillwang** [comment]
@barthy1 

Are you fine to support arm64. Otherwise, I will close this issue. I don't want to support so many linux distributions. That's not my focus.

**Comment by barthy1** [comment]
@ozbillwang  I don't have arm64 hardware to help with problems or verify the build. I can verify if the image build logs are ok/whether arm64 image is available in multi-arch stack.

@masip85 `arm64v8` arch is not supported/available for `alpine/git` at this moment. 
I believe you can create the PR with working code to get arm64 image and provide some evidence that the arm image actually works. But it's up to @ozbillwang to decide.

**Comment by heussd** [comment]
I would love to see `alpine/git` offering images for all possible architectures.

With GitHub Actions and buildx, this can be achieved very easily, as demonstrated [with my fork](https://github.com/heussd/git/tree/actions-multi-arch). [I created a pull request ](https://github.com/alpine-docker/git/pull/27)and add some comments there. Feel free to accept 😄 

[See this fork in action](https://github.com/heussd/fivefilters-full-text-rss-docker/runs/1189898143).

**Comment by masip85** [comment]
@barthy1 git actually works, but I am working on how to pass ssh_agent or secret to the container in order to really use git. But commands without permissions works as expected. 
Buildkit must be used, but: 
https://github.com/docker-snap/docker-snap/issues/1#issuecomment-700837731

**Comment by barthy1** [comment]
@masip85 well, Buildkit as far as I can see you discuss in another issue :)
From my side, initial Dockerfile you provided as sample works for me on `s390x` with `--global` addition to git config
```
FROM alpine
LABEL maintainer Bill Wang <ozbillwang@gmail.com>

RUN apk --update add git less openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

RUN git config --global user.name "xxxx" && \
         git config --global user.email "xxxx"

VOLUME /git
WORKDIR /git

ENTRYPOINT ["git"]
CMD ["--help"]
```
I was also able to pull private git repo on `s390x` using `docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git clone <repo>`, so secrets can be passed.

As I mentioned before I don't have arm hardware to provide you some specific hints :(

**Comment by masip85** [comment]
> I was also able to pull private git repo on s390x using docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git clone <repo>, so secrets can be passed.

Why that command gives you access to your cloud repo?

**Comment by barthy1** [comment]
because in ${HOME} I actually have ssh key to pull the git repo.

**Comment by masip85** [comment]
And you invoke it in the clone command or similar ? Because the ssh-agent of the container doesn't have that key loaded. 

Just as you say I still with permission denied.

**Comment by barthy1** [comment]
in `.ssh` dir on my host I have the ssh private key and ssh config with 
```
Host github.com
     IdentityFile ~/.ssh/github_id_rsa
```
When I run `docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git clone <private_repo>` my `${HOME}/.ssh` dir is shared inside container as `/root/.ssh`. It is default dir to get ssh info, so `git clone` command in container will use the appropriate key by default.

**Comment by ozbillwang** [comment]
will do with #30
