### ISSUE TITLE
Could not fetch origin when the repo is also dockerized

### ISSUE THREAD

**Issue by ymettier** [alpine-docker/git#3]
Hello,

Problem
------------
I'm running a git repository in a docker container. So I have problems to connect from one container to another :

```
# git remote update
Fetching origin
fatal: Unable to find remote helper for 'http'
error: Could not fetch origin
```

Solution
------------
alias git="docker run ... --net=host ..."

I'm not sure that adding `--net=host` for everybody will be better. However, for me, it was the solution.

**Comment by SydOps** [comment]
I am fine to run it without `--net=host`

I update the alias, can you try again?

    alias git="docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git bwits/docker-git-alpine"

**Comment by ymettier** [comment]
Run a git repository in a docker container. Here is how you can do it : http://www.damagehead.com/docker-gitlab/

If you follow this doc (and use the excellent docker container they make with gitlab), you will get your _remote_ like this (I replaced localhost with myserver because I do not use localhost in my case) :
```
$ git clone http://myserver:10080/mygroup/myrepo.git
$ git remote -v
origin	http://myserver:10080/mygroup/myrepo.git (fetch)
origin	http://myserver:10080/mygroup/myrepo.git (push)
```

If you run your simple container anywhere except on myserver, it should work. On myserver, it will not work because the 2 containers (alpine-docker and the one with gitlab) do not communicate.

How to make them communicate ? One easy solution is --net=host. Easy. Another solution is to configure a virtual network inside docker and make the 2 containers use it. Too complex.

IMHO, you should not update the alias (as you did with .gitconfig) with --net=host because few people need it and most people do not need such a specific config. But you could explain the case (better than I) in the README.md and maybe add a link to this issue.

About the .profile, I am also in a specific case (a NAS) : my .profile will be removed every time I reboot my NAS. So I prefer the alias. If you don't mind, keep both in your readme.

There is also a problem with both the alias and your function : $(pwd) does not match the root of the git repo, but the place where you evaluate it. I make an issue for that.

**Comment by SydOps** [comment]
Try to answer your questions one by one.

>Run a git repository in a docker container. Here is how you can do it : http://www.damagehead.com/docker-gitlab/

Yes, I can do that.

>If you follow this doc (and use the excellent docker container they make with gitlab), you will get your remote like this (I replaced localhost with myserver because I do not use localhost in my case) :
```

$ git clone http://myserver:10080/mygroup/myrepo.git
$ git remote -v
origin	http://myserver:10080/mygroup/myrepo.git (fetch)
origin	http://myserver:10080/mygroup/myrepo.git (push)
```
Looks fine for me, plus if you can run with --link and --net option, that's better.

    docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git --link git_gitlab_1:myserver --net=git_default  alpine/git clone http://root@myserver:80/root/test.git

NOTES:  you need change the port to 80, because it is linked directly.


> If you run your simple container anywhere except on myserver, it should work. On myserver, it will not work because the 2 containers (alpine-docker and the one with gitlab) do not communicate.

for this special case, you can add option `--net=git_default`. Use below command to get all docker network list.

    $ docker network ls

> How to make them communicate ? One easy solution is --net=host. Easy. Another solution is to configure a virtual network inside docker and make the 2 containers use it. Too complex.

>IMHO, you should not update the alias (as you did with .gitconfig) with --net=host because few people need it and most people do not need such a specific config. But you could explain the case (better than I) in the README.md and maybe add a link to this issue.

Have explained, use `--net=git_default` better than `--net=host`

> About the .profile, I am also in a specific case (a NAS) : my .profile will be removed every time I reboot my NAS. So I prefer the alias. If you don't mind, keep both in your readme.

You can make the decision if put this function in `.profile` or not. I will update `README`.

>There is also a problem with both the alias and your function : $(pwd) does not match the root of the git repo, but the place where you evaluate it. I make an issue for that.

I found one issue when set alias. Run the alias first time, it will record all path in current folder, if you need to work on another repo, this alias has wrong path on it.
