### ISSUE TITLE
what the heck is the latest tag? Git v1 or git v2?

### ISSUE THREAD

**Issue by red8888** [alpine-docker/git#45]
I'm looking at the docker tags and this is really confusing to me. Why do the latest v2 and v1 tags all have different digests?
<img width="1252" alt="git" src="https://user-images.githubusercontent.com/6265399/164288064-d519d4b3-36db-4823-8112-c3b7bdeda922.png">

What is latest tag? I would expect it to be the same as either the most recent v1 or v2 tag but the digest is different.

**Comment by ozbillwang** [comment]
so there are two type of tag. 

1. start from v, such as v2.34.1, that's git version
2. start from 1.0.x, that's just a semantic versioning in this image. that's good question, it is not very useful. We can delete it and reduce the confusing.
