### ISSUE TITLE
Alpine docker does not support git 2.35.2

### ISSUE THREAD

**Issue by DennisPlaydon** [alpine-docker/git#46]
Hi there, 

We are pulling the latest alpine image and running git commands in CI. However we are running into a `fatal: unsafe repository ('...' is owned by someone else)`. This seems to be a new error due to a [security vulnerability in git](https://github.blog/2022-04-12-git-security-vulnerability-announced/). 

The recommendation is to update to the latest version of git, version `2.35.2`. Would it be possible to release a new version of `alpine/git` so it is possible to upgrade?

Thank you 😃

**Comment by ozbillwang** [comment]
yes, I saw the same error on version 2.34.1 only. that's the latest image generated, which was auto-generated yesterday.

For production usage, please don't use the latest as tag when you pull the image, always stick on a version which have been tested. 

Let me trigger the pipeline to build a new image on v2.35.2

**Comment by ozbillwang** [comment]
Seems we have to wait for the new version available in Alpine.  Let me explain. 

This Dockerfile is to install git via `apk add git` directly, it will always install the latest versin in Alpine. 

But currently latest git version in alpine is `v2.34.2`

but the official git release has been v2.36.0 (https://github.com/git/git/tags)

I have to wait, otherwise, we need adjust our codes to compile and build the git from source codes, that would be totally different cases.

**Comment by ozbillwang** [comment]
unless we switch the base image from `alpine` to `alpine:edge`

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/8954908/164381473-9f55d856-0cbe-4325-827e-2e9858a6dcb2.png">

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/8954908/164381509-a0c4682f-e948-4eea-a90d-4942bea8b11a.png">

**Comment by jaydrogers** [comment]
Thanks for organizing and maintaining this project!

**Just adding a note for others who are attempting to run `git config --global --add safe.directory /git`:**
* 👉 If you run this command before your `git pull` command in CI, then you may have to do an extra step

**Solution:**
- Mount a volume for `/root` in the container

**Example:**
Here is a snippet from my Gitlab deployment:
```yml
script:
  - docker run --rm --pull always -v /home/deploy-user/:/root -v /path/to/my/app:/git alpine/git config --global --add safe.directory /git"
  - docker run --rm --pull always -v /home/deploy-user/:/root -v /path/to/my/app:/git alpine/git pull origin my-branch"
```

**Comment by DennisPlaydon** [comment]
Hey @ozbillwang I see that alpine has [released ](https://pkgs.alpinelinux.org/packages?name=git&branch=v3.16)a new version. Could we update now?
![image](https://user-images.githubusercontent.com/37030744/170138187-c3ac5273-3351-4f68-b063-6c9d8c854eed.png)

**Comment by ozbillwang** [comment]
the free pipeline sets some limitation build time now. i changed the build frequency from daily to weekly. so it is possible to wait for one week to get the latest version

**Comment by ozbillwang** [comment]
The latest tag is [v2.36.2](https://hub.docker.com/layers/git/alpine/git/v2.36.2/images/sha256-77afd5a9d4e2d92c3a82d8313c2f4cf0f043b2b436aa32458d44860e52fd1a24?context=repo) already. 

Close this issu now.
