### ISSUE TITLE
Add riscv64 support

### ISSUE THREAD

**Issue by 6543** [alpine-docker/git#51]
alpine:edge does already provide docker images for it :)

**Comment by 6543** [comment]
you other images should stay at latest, would it be ok to create a specific Dockerfile for this case?

and are pulls welcome?

**Comment by ozbillwang** [comment]
yes, it is

**Comment by 6543** [comment]
@ozbillwang is it ok to bump base image to edge for other arch images too?

yes -> single Dockerfile
no -> specific Dockerfile

**Comment by ozbillwang** [comment]
We discussed about tag with `edge` or `latest`, finally go with `latest`. 

with `image:edge`, I got some unexpected result, sometime.

So the plan can be:

set a feature branch, set the base image to `alpine:edge`, and I can apply the tag as `alpine/git:edge-<version>`

**Comment by ozbillwang** [comment]
change has done in branch `feature/edge`

I can see the images with arch `risc64` now. 

<img width="705" alt="image" src="https://user-images.githubusercontent.com/8954908/194461706-6563a262-cf6c-4f8a-a5a7-415f5dfc0cff.png">

@6543 Please confirm. 

Currently the tags support `risc64` are

* alpine/git:edge
* alpine/git:edge-v2.38.0
* alpine/git:edge-2.38.0

**Comment by ozbillwang** [comment]
the trivy scan is not passed. But that's acceptible, because that's edge version

![image](https://user-images.githubusercontent.com/8954908/194462190-0bd0e070-fc87-4f72-8b69-437eb2c134c1.png)

**Comment by 6543** [comment]
Wow thanks ❤️
