### ISSUE TITLE
Docker is sunsetting Free Team organizations

### ISSUE THREAD

**Issue by ozbillwang** [alpine-docker/git#57]
Got mail from Docker Inc, that `Docker is sunsetting Free Team organizations`

https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

Our Org `alpine` is `docker free team`, if not pay montly, will be closed down by 14th April.

What can we do?

1. pay monthly fee (US$5), but who should pay? 
2. migrate to other free docker registry, such as [github docker registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry), [gitlab container registry](https://docs.gitlab.com/ee/user/packages/container_registry/) 
3. I share my ethereum address, and waiting for the donation, pay for 1 year first (US$60), then we discuss this case later, if we need formally migrate to other platforms.

The same will be applied to all images in this Org.

One problem with plan of $5, it only supports `5,000 image pulls per day` for the whole Org, which is obviously not good enough for this Org. 

![image](https://user-images.githubusercontent.com/8954908/225208152-60872fd4-ea6f-4cb0-a764-1b1242b50ad3.png)

**Comment by superboum** [comment]
Did you consider Docker-Sponsored Open Source Program? 
https://www.docker.com/community/open-source/application/

**Comment by ozbillwang** [comment]
Thanks, I did last week as well.

**Comment by tarneaux** [comment]
I don't think paying $5 a month is the right way to tackle this situation with docker hub: if they don't want to collaborate with opensource, we shouldn't either, and apparently that's what's going to happen.
We don't need to continue using docker hub just because everything is there.
If github can give us this for free, then I'd say take the offer.

**Comment by ozbillwang** [comment]
Get a new mail from Docker Inc, they reserved the decision. Good news to open source community

![image](https://user-images.githubusercontent.com/8954908/227695849-ff73e4a9-8af8-4425-be5a-f74610b77b3c.png)
