### ISSUE TITLE
How can i upgrade the git version in alpine/git:v2.24.3-user ? 

### ISSUE THREAD

**Issue by cappuuuuuu** [alpine-docker/git#61]
I want to user git sparse-out, but it's not support in git v2.24.3, and i want to use non-root, plz .
Thank you !

**Comment by ozbillwang** [comment]
Not sure I got you. the latest git image is `v2.40.1`

![image](https://github.com/alpine-docker/git/assets/8954908/c06d3d19-0378-4ff5-9511-43491075232a)

For non-root usage, I used to maintain in another branch, you can take a reference: https://github.com/alpine-docker/git/blob/feature/non-root/Dockerfile, I didn't work on it for more than 3 years.
