### ISSUE TITLE
Re-enable non-root image builds

### ISSUE THREAD

**Issue by Richard87** [alpine-docker/git#62]
Hi!

Is it possible to start building non-root images again?

Re. https://github.com/alpine-docker/git/tree/feature/non-root

**Comment by Richard87** [comment]
Currently running the image rootless with the user `65534 / nobody` which allows me to clone repos when my ssh keys are mounted in `/.ssh`

**Comment by ozbillwang** [comment]
I have no time to maintain another branch currently. 

regarding your question, did you try to mount `/.ssh` with `-v` 

```
docker run -ti --rm -v /.ssh:/.ssh alpine/k8s sh
```

**Comment by Richard87** [comment]
Hi, yes, mounting .ssh into `/.ssh` works great with the `nobody` user... Thanks, I'm closing this then, also the k8s image is _very_ interresting!
