### ISSUE TITLE
Git pull_request - perl missing in image

### ISSUE THREAD

**Issue by johan974** [alpine-docker/git#63]
During pull_request the error is: 

```
+ git request-pull master ssh://git@gitea-gitea-ssh.default.svc.cluster.local:22/gituser/argocd-demo.git fb20231218-07
/usr/libexec/git-core/git-request-pull: line 115: /usr/bin/perl: not found
```
Looks like perl is missing. 

On further investigation is confirmed that Perl is not in the Alpine docker image. 

```
+ which perl
Is Perl on board? ...
-----EOF perl---
```

This happens both in an older version (2.26) and the newest 2.43.0 version. 

Consequence is that the command does not find a version and cannot be executed. 

After adding perl to the Dockerfile, everything works fine again. I am not an Dockerfile expert, just added Perl via [this example](https://github.com/ytnobody/docker-alpine-perl/blob/master/Dockerfile).

**Comment by ozbillwang** [comment]
thanks, I have added in latest release
